### ISSUE TITLE
`charon dkg` logs the definition hash in base64

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1043]
# 🐞 Bug Report

### Description

```
12:30:24.674 INFO dkg        Connecting to peers... {"definition_hash": "Ug8X9OqADRgr+T/5+qfaV/BwipL0K5ztmutgnELd3pA="}
12:30:35.690 INFO dkg        Connected to peer 1 of 3 {"peer": "sore-hill"}
```

We have updated definition hash to be hex

## 🔥 Error

Above should be `0x520f17f4ea800d182bf93ff9faa7da57f0708a92f42b9ced9aeb609c42ddde90`

**Comment by xenowits** [comment]
This has already been fixed in the newer versions: 
https://github.com/ObolNetwork/charon/blob/6925c403336b2665a5d6f5c5960ade90e720f142/dkg/dkg.go#L98
https://github.com/ObolNetwork/charon/blob/6925c403336b2665a5d6f5c5960ade90e720f142/dkg/dkg.go#L134

Note that `"%#x"` returns a `0x` formatted hex string.
