### ISSUE TITLE
Investigate 5s `attestation_data` vapi latencies

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1472]
## Problem to be solved

Most nodes with a teku VC are showing 5s `attestation_data` validator API 90% latencies. 

Figure out why this is, and what we can do about decreasing this.

Maybe the VC queries attestation data at the start of the slot instead of 1/3 in (so at least 4s before we schedule the duty). If so, is this correct?

<img width="725" alt="image" src="https://user-images.githubusercontent.com/29249923/203240138-5a796348-ae58-4e67-99f8-0f0bf4b67b91.png">

## Proposed solution

Add duty completion delay metrics (after start of the slot) (as well as consensus complete). Then we can at least see if the duties are taking long of the VC is querying early.

**Comment by dB2510** [comment]
Investigation Results:
- 5s `attestation_data` latencies were because of VC querying attestation data at the start of slot.
- VCs query `attestation_data` based on two conditions (whichever happens first):
   1. Received a head update event OR
   2. One-third of slot is passed
- So if `attestation_data` latency is > 4s (one-third of slot) then VC queried `attestation_data` at the start of slot, which means 1st condition happened first.
- And if `attestation_data` latency is < 4s then VC queried `attestation_data` one-third into the slot, which means 2nd condition happened first.
