### ISSUE TITLE
Make DKG program fault tolerant during 'connecting to peers' phase. 

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1475]
## Problem to be solved

We originally made the DKG connection brittle, and failed fast when a connection was dropped. This is making asychronous DKGs difficult. 

## Proposed solution

Let's not abort if we lose a peer, and instead try and recover the connection later. At the end of the DKG, we should keep the process running for one extra second while we attempt to check if all peers are still connected, and if it appears they are not we should print a big warning saying something to the effect that "There may have been a participant that had connection issues during the DKG, please confirm with every operator that their private key shares were created in `.charon/validator_keys`. 

### In Scope

Updating our tests to assert the DKG command can handle a whole number of random process exits. 

### Out of Scope

If the DKG failed, we shouldn't auto retry it, we should just auto reconnect in the 'waiting to connect to peers' phase, not bang smack in the middle of the ceremony phase, we can outright error then, preferably with a helpful error.

**Comment by corverroos** [comment]
Note there is a simple work around for this. Just wrap the DKG command in a `while-not-loop`
```
while ! docker run --rm -v "$(pwd):/opt/charon" obolnetwork/charon:v0.12.0 dkg; do echo Retrying DKG; done
```

**Comment by corverroos** [comment]
Suggest:
 - Refactor `client.AwaitConnected` into `client.IsConnected`
 - Once all clients are connected then call new method `client.DisableReconnect`
 - Refactor `c.sendMsgs` to return `(relayErr bool, connErr bool, otherErr error)`.
 - Refactor `c.Run` into two states based on internal `c.reconnect bool` state:
   - If `c.reconnect=true`, reconnect on either `relayErr` or `connErr` with `retry=true`.
   - If `c.reconnect=false`, only reconnect on `relayErr` with `retry=false`.
   - Call `c.clearConnected` when `c.sendMsgs` returns
 - add `defer s.clearConnected(pID)` to `server`
 - Move "(dis)connected to peer) logging from server to client:
   - Log "connected" when `c.connect` succeeded not due to and it wasn't due relayErr.
   - Log "disconnected" before calling `c.connect` and it is due to `connErr`.

**Comment by corverroos** [comment]
Suggest test cases:
 - 2 of 3 peers connected, 2 drops, then reconnects, then 3 connects and $$$
 - 2 of 3 peers connected, 1 and 2 drops, then both reconnect, then 2 drops and reconnects, then 3th connects and $$$
 - etc
