### ISSUE TITLE
Teku missing attestations

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1585]
## Problem to be solved

Teku VC missed attestations in charon-perf-1 cluster with warns:
```
2023-01-04 17:51:44 | 2023-01-04 15:51:44.004 WARN  - Skipping aggregation for slot 4694957 due to unexpected delay in slot processing
2023-01-04 17:51:44 | 2023-01-04 15:51:44.004 WARN  - Skipping attestation for slot 4694957 due to unexpected delay in slot processing
2023-01-04 17:51:44 | 2023-01-04 15:51:44.003 WARN  - Skipping block creation for slot 4694957 due to unexpected delay in slot processing
```

- Slot ticked at: 15:51:24.000
- So these warnings were logged 20s after that. 
- No charon logs seen for this slot

## Proposed solution

Investigate and figure out what is going on.

**Comment by corverroos** [comment]
Looking at teku code, this seems to pure scheduling issue, https://github.com/ConsenSys/teku/blob/master/validator/beaconnode/src/main/java/tech/pegasys/teku/validator/beaconnode/TimeBasedEventAdapter.java#L96.

The scheduled task isn't triggered at the expected time but much later. 

I'm guessing this is due to resource contraints, either cpu, memory, garbage collection....

Suggest checking whether the VC is overloaded

**Comment by corverroos** [comment]
Digging deeper, it seems the teku scheduler/asyncrunner only uses a few threads (number of CPUs) thread. This could be the cause of these delays since it might wait for 5 queries to timeout before attempting more.... https://github.com/ConsenSys/teku/blob/master/infrastructure/serviceutils/src/main/java/tech/pegasys/teku/service/serviceutils/ServiceConfig.java#L95

**Comment by dB2510** [comment]
Teku VCs in charon-perf-1 cluster are causing `VC missing some validators` readyz status. This is due to delay in `get_validators` validatorapi call which should be called at the start of each epoch.
![Screenshot 2023-01-10 at 12 18 16 PM](https://user-images.githubusercontent.com/37813203/211489168-db3a4bf2-4e57-43f2-a4b2-5583512fe57c.png)
Here's the snapshot of validatorapi request rate graph which shows >10m delay in get_validators call:
![Screenshot 2023-01-10 at 12 34 24 PM](https://user-images.githubusercontent.com/37813203/211489403-5aed58a3-a72b-42ac-9654-f90e2c7d2211.png)

**Comment by corverroos** [comment]
this is working now
