### ISSUE TITLE
Swallow 409s returned to the `--publish` command gracefully

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#2254]
# 🎯 Problem to be solved

When a DKG is complete, every node races to `publish` it. Most of them get hit with a `409 warn` log that we output to console. We see a number of people return to us with a 'I got this error, is everything okay?'. 

# 🛠️ Proposed solution
- [ ] Approved design doc: *link*
- [ ] Core team consensus on the proposed solution

I think it is safe to swallow this error and move it from `warn` to `debug`. 

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

# 👐 Additional acceptance criteria

Something that might be interesting, is on the API side, if we get a POST to that endpoint, and we already have an entry present for that hash, we will return a 409, but potentially if its cheap/important, we could check if what we are being given exactly matches what's in the DB. If so, this is a normal race condition. If they are different, this could be worthy of warning that something fishy is going on and conflicting lock files are attempting to be pushed to the API and we should see if something is afoot. 

# ❌ Out of Scope

.

**Comment by corverroos** [comment]
I would rather return a 200 from the obol-api on duplicate identical writes since the result is the same. That results in a idempotent API which is great UX. It is super clear that 409 can be ignored in all cases, some other API that we publish to might return 409 due to something else, which should result in retry instead of swallowing. So this feels like tight coupling between our specific obol-api and this specific publish logic. I would prefer to keep things decoupled.

**Comment by corverroos** [comment]
Closing as we decided to make the obol-api idempotent, see discord: https://discord.com/channels/930779837218562078/1113082254160310272
