### ISSUE TITLE
Make the folder output structure from `create cluster` compatible with `charon run` defaults

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#2302]
# 🎯 Problem to be solved

The output format of `create cluster` is a format that `charon run` doesn't expect. Users need to either rename the folder or override the paths on `run`. It would be better UX if the output of `create` neatly fit with the output of `dkg`. So CDVN could be used in the 'create a cluster alone' flow without manual intervention. 

# 🛠️ Proposed solution
- [ ] Approved design doc: *link*
- [ ] Core team consensus on the proposed solution

Describe the solution to be implemented

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by gsora** [comment]
Right now `create cluster` creates the following directory tree:

```
.charon
└── cluster
    ├── node0
    ├── node1
    ├── node2
    └── node3
```

Instead of nesting `cluster` under `.charon` I propose we output it in the terminal's current working directory, so that users have immediate feedback on where the newly-created cluster files are and can act on them easily:

```
cluster
├── node0
├── node1
├── node2
└── node3
```

`--cluster-dir` already supports writing its output in arbitrary directories, the only change needed is in its default value

```go
func bindClusterFlags(flags *pflag.FlagSet, config *clusterConfig) {
	// ...other flags
	flags.StringVar(&config.ClusterDir, "cluster-dir", "cluster", "The target folder to create the cluster in.")
	// ...other flags
}
```

**Comment by gsora** [comment]
@corverroos suggested, for simplicity sake, to create `nodeX` directories straight into the current working directory.

Think `mkdir`, when you call it, it automatically creates a directory _in the current directory_.

I feel this is the way to go: this behavior is simple, obvious and well-understood.

**Comment by OisinKyne** [comment]
Fine by me
