### ISSUE TITLE
Race in AggSigDB unit test

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2546]
# 🐞 Bug Report

### Description

AggSigDB test `TestDutyExpiration` has a race condition which causes builds and PRs to fail, [see](https://github.com/ObolNetwork/charon/actions/runs/5857191067/job/15878503330?pr=2543). The test has been disabled.

Fix the race and enable the test.

**Comment by Aleksao998** [comment]
Hey, nice to meet you all! 👋
I've been going through your repo and really like the work you've put into it. 

I've identified the root cause of the race condition in the TestDutyExpiration test. And open PR with a fix:
https://github.com/ObolNetwork/charon/pull/2561. Looking forward to your feedback 🚀
