### ISSUE TITLE
Spike on generic exits

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2848]
# 🎯 Problem to be solved

We need to do a technical spike to figure out possible approaches to support generic exits (see [PRD](https://docs.google.com/document/d/140kknAtq2MWIWPUMIH4odoHtO0PhnHcP3EjMuAVhwU0/edit)).

# 🛠️ Proposed solution

Spike to see if we can craft a generic solution to the problem of exiting distributed validators. The output of this spike should be a design doc containing the research findings.

Note that we also have a [design doc](https://docs.google.com/document/d/1CWnqeuPTgb67igGdEo83Ca7TX8lSCak1Ide_4zI6pio/edit#heading=h.mssb0822zapb) that could be useful for this spike.

# 🧪 Tests

None

**Comment by gsora** [comment]
## The charon exit submit-partial-exit command

This Charon command is a middle ground between a `lido-dv-exit`-style deployment and full manual exit [through the beacon node](https://docs.obol.tech/docs/v0.19.0/int/quickstart/quickstart-exit).

`charon exit submit-partial-exit` submits a partial exit for a specified validator through the CLI, and uses Obol API as its aggregation point -- just like `lido-dv-exit`.

An accessory command, `charon exit full-exit` will download the full exit message from Obol API if available, and broadcast it.

Both commands _need a beacon node to function_, because they need to:
- fetch the validator index during `submit-partial-exit`
- broadcast the full exit message during `full exit`

The commands by design don't allow for multiple validator to be processed at the same time, but their composable nature allow for building simple automation scripts.

Exiting a validator would work like this:
- user A invokes `charon exit submit-partial-exit --beacon-node http://beaconnode-address 0xabcd... `
- waits until threshold operators also ran the same command
- any user runs `charon exit full-exit --beacon-node http://beaconnode-address 0xabcd...`
