### ISSUE TITLE
QBFT: round should be unsigned

### ISSUE THREAD

**Issue by leolara** [ObolNetwork/charon#537]
## Problem to be solved

There cannot be negative rounds, however the type for round is `int64`. Also MsgType, uponRule and processes (which include source) cannot be negative

## Proposed solution

Change the type for round, and message type to `uint64`, also in MsgType, and processes values like Source()

### Why this matters

By putting `int64` we are indicating other developers that the value can be negative and that those values are meaningful.

**Comment by corverroos** [comment]
The most accurate type is probably `byte` since rounds should never really very high. Just `uint` is also better than `uint64` for that matter.

But, I'm not sure that add much value. I would actually just make it `int`, the default "number". Same to how `len() int` returns `int`, not `uint`. Specifying unsigned everywhere feels like to attracts so much attention, to something that isn't really important.

**Comment by leolara** [comment]
+ Code is documentation
 + This caused compatibility problems with eth2 libraries for example in epoch.
 + It doesn't provide much, but it should have been catched in code review.

From what you are saying it sounds like `uint32` would be the right type.

I think `len` returning `int` is because indexes if arrays are `int` to allow to do complex calculations without overflow.

**Comment by leolara** [comment]
Also, I think what you are doing is the common style in C language, but in Go, and in what I have seen for ethereum it is more common to use unsigned for unsigned

**Comment by corverroos** [comment]
So this package isn't related to eth2, so I do not think we need to follow the eth2 spec.
