### ISSUE TITLE
Create a `charon create exit` command, to prepare exit data for an activated DV in a cluster

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#553]
## Problem to be solved

We will create many testnet distributed validators. We should not abandon them offline to bleed to 16eth before eviction, instead we should exit them from the network with a `voluntary exit`  message. https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#voluntary-exits

## Proposed solution

~~When perfoming a cluster creation, we also:~~

It turns out you can only craft an exit message for a validator once you know its index. So preparing an exit message at key creation stage is not possible. https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#voluntaryexit

Instead, a means to craft an exit message will need to be built into an in-operation cluster. This will be a larger undertaking and needs architecting. Potentially another command like `charon create exit` could work, it needs to query a BN for the pubkeys validator index before getting it threshold signed. 

### Out of Scope

Broadcasting the created exit data can be another ticket for the docs/readmes.

**Comment by leolara** [comment]
@corverroos @OisinKyne please let me know if you have any suggestions about how to implement this

**Comment by leolara** [comment]
@dB2510 @xenowits also you too, please let me know if you have any suggestions about how to implement this

**Comment by xenowits** [comment]
we need to have good amount of discussion on this. Having another command `charon create exit` is probably fine. Prysm has a command for voluntary exits: `./prysm.sh validator accounts voluntary-exit`, maybe we can start by exploring that. since a `VoluntaryExit` object also contains `epoch` (specwise: Earliest epoch when voluntary exit can be processed), i wonder how the epoch is calculated in advance.

**Comment by leolara** [comment]
@xenowits I think first we would need to find out if the validators have a API endpoint to sign this, otherwise it would be impossible.

Then I would make the `charon create exit` command communicate via P2P with all the nodes and request the exit, which would require the validators. Then the command itself can do the aggregation I guess.

We also should consider how to authenticate the command with the nodes, otherwise anyone could request the signed voluntary exit.

**Comment by leolara** [comment]
https://docs.google.com/document/d/1OtvTQ_7ftcKY2n62m3o6HSFw7W5hTm94b-HtugfjmWA/edit?usp=sharing
