### ISSUE TITLE
Make compose tests more robust

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#992]
## Problem to be solved

Compose integration tests only fail if the docker containers exit unexpectedly. Failing tests due to alerts thresholds being triggered due to missed duties or high error rate doesn't seem to work (the tests always pass). Also, debugging the output of compose tests is very hard due to the large amount of output that breaks the github UI.
 
## Proposed solution

Break each compose test into its own github action step/job/task?
Or write each test output to a file and make that downloadable from github action results/artifacts.
Figure out why alerts are not being triggered
Figure out why prometheus cannot be polled sporadically.

**Comment by dB2510** [comment]
The purpose of this ticket has been served. We have 2 tickets now related to compose tests:
- https://github.com/ObolNetwork/charon/issues/860
- https://github.com/ObolNetwork/charon/issues/1471

Things that were fixed as part of this ticket:
- Upload docker-compose logs for each test as github action artefact.
- Fix prometheus alerts by separating docker compose build step from docker-compose up.
- Found out issues related to `very_large` smoke test that it wasn't starting in the first place since it takes time in lock step and while building and starting containers which crosses default timeout of 15s.
- Created #1471 for `very_large`.
- Retention time of action artefacts is 3 days to avoid storage pricing issues.
